/**:
  camera:
    ros__parameters:
      enable_accel: false
      enable_color: true
      enable_gyro: false
      enable_depth: false
      enable_infra1: false
      enable_infra2: false
      enable_rgbd: false
      rgb_camera.color_profile: 640x480x60
      rgb_camera.color_format: 'RGB8'
      align_depth.enable: false
      serial_no: "032522250135"
      camera.color.image_raw.enable_pub_plugins: ['image_transport/raw']
