/**:
  camera:
    ros__parameters:
      enable_accel: false
      enable_color: true
      enable_gyro: false
      enable_depth: false
      enable_infra1: false
      enable_infra2: false
      enable_rgbd: false
      depth_module.color_profile: 424x240x60
      depth_module.color_format: 'RGB8'
      align_depth.enable: false
      serial_no: "128422271784"
      camera.color.image_rect_raw.enable_pub_plugins: ['image_transport/raw']
# D405
