# Dataset settings
dataset_dir: "/home/ben347/all/data/dual_corn/"
local_dataset_dir: "/home/qutrll/data/pot_pick_place_10hz/"
batch_size: 8
sequence_length: 1
split: 0.95

# Model settings
learning_rate: 3e-5
# learning_rate: 1e-3

# Training settings
resume_training: False
resume_step: 0
max_steps: 1000000
validation_interval: 1000
validation_steps: 100
checkpoint_interval: 10000
checkpoint_dir: "/scratch3/ben347/all/data/dual_corn_ckpt/1/"
local_checkpoint_dir: "/home/qutrll/data/pot_pick_place_ckpt_10hz/1/"

# Architecture settings
architecture: "convnext_tiny + MLP"
